import type { Brand, Post, Product } from "./types";

/**
 * Donnees de demonstration.
 * Elles servent tant que Supabase n'est pas branche, pour que
 * `npm run dev` affiche un site vivant des la premiere minute.
 * Une fois la base remplie, elles ne sont plus jamais utilisees.
 */

export const DEMO_BRANDS: Brand[] = [
  {
    id: "demo-aryes",
    slug: "engineered-by-aryes",
    name: "Engineered By Aryes",
    tagline: "Minimalisme français, séries limitées",
    description:
      "Label français au vocabulaire épuré : chemises, pantalons, mailles et bijoux en argent. Des séries courtes, des noms de pièces empruntés à une poésie japonaise, et une obsession pour la coupe plutôt que pour le logo.",
    country: "France",
    city: "Paris",
    founded_year: 2022,
    categories: ["Minimalisme", "Maille", "Bijoux"],
    price_tier: "premium",
    website_url: "https://shoparyes.fr",
    shop_url: "https://shoparyes.fr",
    instagram: "engineeredbyaryes",
    logo_url: null,
    cover_url: null,
    featured: true,
    status: "published",
    published_at: "2026-07-02",
  },
  {
    id: "demo-pollen",
    slug: "pollen-fabrics",
    name: "Pollen Fabrics",
    tagline: "Le denim comme matière première",
    description:
      "Un travail du denim brut et des coupes larges, pensé pour durer plus d'une saison. Production en petites quantités, pièces retravaillées à la main.",
    country: "France",
    city: null,
    founded_year: 2023,
    categories: ["Denim", "Streetwear"],
    price_tier: "intermediaire",
    website_url: null,
    shop_url: null,
    instagram: "pollenfabrics",
    logo_url: null,
    cover_url: null,
    featured: true,
    status: "published",
    published_at: "2026-06-18",
  },
];

const brandRef = (b: Brand) => ({ id: b.id, slug: b.slug, name: b.name });

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo-p1",
    brand_id: "demo-aryes",
    slug: "chemise-structuree-coton-lave",
    name: "Chemise structurée, coton lavé",
    price_cents: 14500,
    compare_at_cents: null,
    currency: "EUR",
    sizes: [],
    size_label: "Taille",
    image_url: null,
    images: [],
    description: "",
    available: true,
    source_id: null,
    shop_url: "https://shoparyes.fr",
    categories: ["Chemise"],
    featured: true,
    status: "published",
    position: 0,
    brand: brandRef(DEMO_BRANDS[0]),
  },
  {
    id: "demo-p2",
    brand_id: "demo-aryes",
    slug: "collier-argent-925",
    name: "Collier argent 925",
    price_cents: 8900,
    compare_at_cents: null,
    currency: "EUR",
    sizes: [],
    size_label: "Taille",
    image_url: null,
    images: [],
    description: "",
    available: true,
    source_id: null,
    shop_url: "https://shoparyes.fr",
    categories: ["Bijoux"],
    featured: false,
    status: "published",
    position: 1,
    brand: brandRef(DEMO_BRANDS[0]),
  },
  {
    id: "demo-p3",
    brand_id: "demo-pollen",
    slug: "write-denim-pant",
    name: "Write Denim Pant",
    price_cents: 11000,
    compare_at_cents: null,
    currency: "EUR",
    sizes: [],
    size_label: "Taille",
    image_url: null,
    images: [],
    description: "",
    available: true,
    source_id: null,
    shop_url: "https://www.instagram.com/pollenfabrics/",
    categories: ["Denim"],
    featured: true,
    status: "published",
    position: 0,
    brand: brandRef(DEMO_BRANDS[1]),
  },
];

export const DEMO_POSTS: Post[] = [
  {
    id: "demo-po1",
    slug: "premiere-selection-aryes",
    title: "La sélection Aryes",
    caption:
      "Trois pièces qui résument la démarche : une coupe, une matière, aucun logo.",
    image_url: null,
    images: [],
    image_alt: "",
    keywords: ["minimalisme", "made in france", "maille"],
    brand_id: "demo-aryes",
    instagram_url: "https://www.instagram.com/newave.sphere/",
    tiktok_url: null,
    status: "published",
    published_at: "2026-07-28",
    brand: brandRef(DEMO_BRANDS[0]),
  },
  {
    id: "demo-po2",
    slug: "pollen-le-denim-brut",
    title: "Pollen, le denim brut",
    caption:
      "Ce que ça change de porter un denim qui n'a pas été lavé quinze fois avant toi.",
    image_url: null,
    images: [],
    image_alt: "",
    keywords: ["denim", "streetwear", "marque indé"],
    brand_id: "demo-pollen",
    instagram_url: "https://www.instagram.com/newave.sphere/",
    tiktok_url: null,
    status: "published",
    published_at: "2026-07-11",
    brand: brandRef(DEMO_BRANDS[1]),
  },
];
